spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tenwonmoa
    username: ${db.user:root}
    password: ${db.password:root1234}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
  flyway:
    baseline-on-migrate: true

jwt:
  header: Authorization
  issuer: tenwonmoa
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds-millis: 3600000 # 1시간 = 3,600,000ms
  refresh-expiry-seconds-millis: 1209600000 # 2주 = 1000ms * 60 * 60 * 24 * 14

app:
  authorized-redirect-uris:
    - http://localhost:3000/oauth2/redirect
    - https://team-10jo-10wonmoa-fe.vercel.app/oauth2/redirect