spring:
  datasource:
    url: jdbc:h2:mem:loadbook;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100