spring:
  profiles:
    default: local

jwt:
  header: token
  issuer: tenwonmoa
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 3600000 # 1시간 = 3,600,000ms
