openapi: 3.0.1
info:
  title: Tenwonmoa API
  description: Tenwonmoa API description
  version: 1.0.0
servers:
- url: http://3.39.184.232:8080
tags: []
paths:
  /api/v1/budgets:
    post:
      tags:
      - api
      operationId: budget-create
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/api-v1-budgets1364090725'
            examples:
              budget-create:
                value: "{\"amount\":1000,\"registerDate\":\"2022-08-09\",\"userCategoryId\"\
                  :1}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-budgets-640988555'
              examples:
                budget-create:
                  value: "{\"id\":1}"
  /api/v1/statistics:
    get:
      tags:
      - api
      operationId: statistics-find-
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-statistics-1753393928'
              examples:
                statistics-find-month:
                  value: "{\"year\":2022,\"month\":10,\"incomeTotalSum\":60,\"expenditureTotalSum\"\
                    :132,\"incomes\":[{\"name\":\"용돈\",\"total\":30,\"percent\":50.0},{\"\
                    name\":\"상여\",\"total\":20,\"percent\":33.33},{\"name\":\"금융소득\
                    \",\"total\":10,\"percent\":16.67}],\"expenditures\":[{\"name\"\
                    :\"교통/차량\",\"total\":45,\"percent\":34.09},{\"name\":\"문화생활\"\
                    ,\"total\":44,\"percent\":33.33},{\"name\":\"마트/편의점\",\"total\"\
                    :43,\"percent\":32.58}]}"
                statistics-find-year:
                  value: "{\"year\":2022,\"month\":null,\"incomeTotalSum\":60,\"expenditureTotalSum\"\
                    :132,\"incomes\":[{\"name\":\"용돈\",\"total\":30,\"percent\":50.0},{\"\
                    name\":\"상여\",\"total\":20,\"percent\":33.33},{\"name\":\"금융소득\
                    \",\"total\":10,\"percent\":16.67}],\"expenditures\":[{\"name\"\
                    :\"교통/차량\",\"total\":45,\"percent\":34.09},{\"name\":\"문화생활\"\
                    ,\"total\":44,\"percent\":33.33},{\"name\":\"마트/편의점\",\"total\"\
                    :43,\"percent\":32.58}]}"
  /api/v1/account-book/search:
    get:
      tags:
      - api
      operationId: search-account-book
      parameters:
      - name: categories
        in: query
        description: 유저카테고리 아이디
        required: true
        schema:
          type: string
      - name: minprice
        in: query
        description: 최소 가격
        required: true
        schema:
          type: string
      - name: maxprice
        in: query
        description: 최대 가격
        required: true
        schema:
          type: string
      - name: start
        in: query
        description: 시작 등록일
        required: true
        schema:
          type: string
      - name: end
        in: query
        description: 종료 등록일
        required: true
        schema:
          type: string
      - name: content
        in: query
        description: "지출, 수입의 내용"
        required: true
        schema:
          type: string
      - name: size
        in: query
        description: 페이지의 사이즈
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: 페이지 번호
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-account-book-search-1060074379'
              examples:
                search-account-book:
                  value: |-
                    {
                      "results" : [ {
                        "registerDate" : "2022-08-09",
                        "amount" : 10000,
                        "content" : "점심",
                        "id" : 1,
                        "type" : "EXPENDITURE",
                        "categoryName" : "식비"
                      }, {
                        "registerDate" : "2022-08-09",
                        "amount" : 50000,
                        "content" : "용돈",
                        "id" : 1,
                        "type" : "INCOME",
                        "categoryName" : "용돈"
                      } ],
                      "currentPage" : 1,
                      "nextPage" : 2,
                      "incomeSum" : 50000,
                      "expenditureSum" : 10000
                    }
  /api/v1/incomes/:
    post:
      tags:
      - api
      operationId: income-create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-incomes-incomeId1988379506'
            examples:
              income-create:
                value: "{\"registerDate\":\"2022-08-09T04:14:00.916932\",\"amount\"\
                  :1000,\"content\":\"content\",\"userCategoryId\":1}"
              income-create-fail:
                value: "{\"registerDate\":\"2022-08-09T04:14:00.953506\",\"amount\"\
                  :1000,\"content\":\"content\",\"userCategoryId\":1}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes--373420824'
              examples:
                income-create:
                  value: "{\"id\":1}"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes-incomeId-940438351'
              examples:
                income-create-fail:
                  value: "{\"messages\":[\"해당 사용자 카테고리는 존재하지 않습니다.\"],\"status\":400}"
  /api/v1/incomes/{incomeId}:
    get:
      tags:
      - api
      operationId: income-f
      parameters:
      - name: incomeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes-incomeId-940438351'
              examples:
                income-find-by-id-fail:
                  value: "{\"messages\":[\"수입 정보가 존재하지 않습니다.\"],\"status\":400}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes-incomeId-1674408626'
              examples:
                income-find-by-id:
                  value: "{\"id\":1,\"registerDate\":\"2022-08-09T04:14:00.973877\"\
                    ,\"amount\":1000,\"content\":\"content\",\"userCategoryId\":1,\"\
                    categoryName\":\"용돈\"}"
        "403":
          description: "403"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes-incomeId-940438351'
              examples:
                income-forbidden:
                  value: "{\"messages\":[\"권한이 없습니다.\"],\"status\":403}"
    put:
      tags:
      - api
      operationId: income-update
      parameters:
      - name: incomeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-incomes-incomeId1988379506'
            examples:
              income-update:
                value: "{\"registerDate\":\"2022-08-09T04:13:59.708878\",\"amount\"\
                  :2000,\"content\":\"updateContent\",\"userCategoryId\":2}"
              income-update-fail:
                value: "{\"registerDate\":\"2022-08-09T04:14:00.876518\",\"amount\"\
                  :2000,\"content\":\"updateContent\",\"userCategoryId\":2}"
      responses:
        "204":
          description: "204"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-incomes-incomeId-940438351'
              examples:
                income-update-fail:
                  value: "{\"messages\":[\"수입 정보가 존재하지 않습니다.\"],\"status\":400}"
    delete:
      tags:
      - api
      operationId: income-delete
      parameters:
      - name: incomeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
components:
  schemas:
    api-v1-incomes-incomeId-940438351:
      type: object
      properties:
        messages:
          type: array
          description: 예외 메시지
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        status:
          type: number
          description: 에러 코드
    api-v1-statistics-1753393928:
      type: object
      properties:
        incomes:
          type: array
          items:
            type: object
            properties:
              total:
                type: number
                description: 총 합
              name:
                type: string
                description: 카테고리 이름
              percent:
                type: number
                description: 비율
        month:
          description: 월
          oneOf:
          - null
          - type: number
        year:
          type: number
          description: 년도
        expenditures:
          type: array
          items:
            type: object
            properties:
              total:
                type: number
                description: 총 합
              name:
                type: string
                description: 카테고리 이름
              percent:
                type: number
                description: 비율
        incomeTotalSum:
          type: number
          description: 수입 총 합계
        expenditureTotalSum:
          type: number
          description: 지출 총 합계
    api-v1-account-book-search-1060074379:
      type: object
      properties:
        nextPage:
          type: number
          description: 다음 페이지
        incomeSum:
          type: number
          description: 수입의 총합
        currentPage:
          type: number
          description: 현재 페이지
        results:
          type: array
          description: "검색된 지출, 수입 데이터"
          items:
            type: object
            properties:
              amount:
                type: number
                description: 금액
              id:
                type: number
                description: 지출 or 수입의 아이디
              type:
                type: string
                description: 지출 or 수입 종류
              categoryName:
                type: string
                description: 카테고리 이름
              content:
                type: string
                description: 내용
              registerDate:
                type: string
                description: 등록일
        expenditureSum:
          type: number
          description: 지출의 총합
    api-v1-incomes-incomeId1988379506:
      type: object
      properties:
        amount:
          type: number
          description: 수입 금액
        userCategoryId:
          type: number
          description: 유저 카테고리 ID
        content:
          type: string
          description: 내용
        registerDate:
          type: string
          description: 수입 등록 날짜
    api-v1-incomes--373420824:
      type: object
      properties:
        id:
          type: number
          description: 생성된 수입 아이디
    api-v1-budgets1364090725:
      type: object
      properties:
        amount:
          type: number
          description: 예산 금액
        userCategoryId:
          type: number
          description: 유저 카테고리 ID
        registerDate:
          type: string
          description: 예산 등록 날짜
    api-v1-incomes-incomeId-1674408626:
      type: object
      properties:
        amount:
          type: number
          description: 수입 금액
        userCategoryId:
          type: number
          description: 유저 카테고리 ID
        id:
          type: number
          description: 수입 ID
        categoryName:
          type: string
          description: 카테고리 이름
        content:
          type: string
          description: 내용
        registerDate:
          type: string
          description: 수입 등록 날짜
    api-v1-budgets-640988555:
      type: object
      properties:
        id:
          type: number
          description: 생성된 예산 아이디
