name: Tenwonmoa CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  tenwonmoa-ci:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          submodules: true

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: build docker-compose
        run: docker-compose up -d

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build